/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyProject;

import java.awt.*;

/**
 *
 * @author Md. Younus Hossain Ahsan
 */

public class Information_Panel extends javax.swing.JFrame {

    public Information_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Patient_Info = new javax.swing.JButton();
        Medicine_Info = new javax.swing.JButton();
        Test_List = new javax.swing.JButton();
        All_Prescriptions = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Chamber_Info = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Patient_Info.setBackground(new java.awt.Color(232, 245, 253));
        Patient_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Patient_Info.setText("Patient Info");
        Patient_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Patient_Info.setContentAreaFilled(false);
        Patient_Info.setOpaque(true);
        Patient_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Patient_InfoMouseMoved(evt);
            }
        });
        Patient_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patient_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Patient_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Patient_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Patient_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Patient_InfoMouseReleased(evt);
            }
        });
        Patient_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Patient_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 200, 45));

        Medicine_Info.setBackground(new java.awt.Color(232, 245, 253));
        Medicine_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Medicine_Info.setText("Medicine Info");
        Medicine_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Medicine_Info.setContentAreaFilled(false);
        Medicine_Info.setOpaque(true);
        Medicine_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Medicine_InfoMouseMoved(evt);
            }
        });
        Medicine_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Medicine_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Medicine_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Medicine_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Medicine_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Medicine_InfoMouseReleased(evt);
            }
        });
        Medicine_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Medicine_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Medicine_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 200, 45));

        Test_List.setBackground(new java.awt.Color(232, 245, 253));
        Test_List.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Test_List.setText("Test List");
        Test_List.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Test_List.setContentAreaFilled(false);
        Test_List.setOpaque(true);
        Test_List.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Test_ListMouseMoved(evt);
            }
        });
        Test_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Test_ListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Test_ListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Test_ListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Test_ListMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Test_ListMouseReleased(evt);
            }
        });
        Test_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test_ListActionPerformed(evt);
            }
        });
        getContentPane().add(Test_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 200, 45));

        All_Prescriptions.setBackground(new java.awt.Color(232, 245, 253));
        All_Prescriptions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        All_Prescriptions.setText("All Prescriptions");
        All_Prescriptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        All_Prescriptions.setContentAreaFilled(false);
        All_Prescriptions.setOpaque(true);
        All_Prescriptions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                All_PrescriptionsMouseMoved(evt);
            }
        });
        All_Prescriptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                All_PrescriptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                All_PrescriptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                All_PrescriptionsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                All_PrescriptionsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                All_PrescriptionsMouseReleased(evt);
            }
        });
        All_Prescriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                All_PrescriptionsActionPerformed(evt);
            }
        });
        getContentPane().add(All_Prescriptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 200, 45));

        Back.setBackground(new java.awt.Color(232, 245, 253));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Back.setContentAreaFilled(false);
        Back.setOpaque(true);
        Back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BackMouseMoved(evt);
            }
        });
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 200, 45));

        Chamber_Info.setBackground(new java.awt.Color(232, 245, 253));
        Chamber_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Chamber_Info.setText("Chamber Info");
        Chamber_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Chamber_Info.setContentAreaFilled(false);
        Chamber_Info.setOpaque(true);
        Chamber_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Chamber_InfoMouseMoved(evt);
            }
        });
        Chamber_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chamber_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Chamber_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Chamber_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Chamber_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Chamber_InfoMouseReleased(evt);
            }
        });
        Chamber_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chamber_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Chamber_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 200, 45));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/+.png"))); // NOI18N
        jLabel4.setText(" Information Panel ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/icon_2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, 160));

        icon.setBackground(new java.awt.Color(255, 255, 255));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/bg4.jpg"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Patient_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_InfoMouseMoved
        Patient_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Patient_InfoMouseMoved

    private void Patient_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_InfoMouseClicked
        Patient_Info.setBackground(new Color(0,0,255).brighter());
        Patient_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Patient_InfoMouseClicked

    private void Patient_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_InfoMouseEntered
        Patient_Info.setBackground(new Color(0,153,255).brighter());
        Patient_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Patient_InfoMouseEntered

    private void Patient_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_InfoMouseExited
        Patient_Info.setBackground(new Color(232,245,253));
        Patient_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Patient_InfoMouseExited

    private void Patient_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_InfoMousePressed
        Patient_Info.setBackground(new Color(0,0,255).brighter());
        Patient_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Patient_InfoMousePressed

    private void Patient_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_InfoMouseReleased
        Patient_Info.setBackground(new Color(232,245,253));
        Patient_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Patient_InfoMouseReleased

    private void Patient_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_InfoActionPerformed

        new Patient_Info().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_Patient_InfoActionPerformed

    private void Medicine_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Medicine_InfoMouseMoved
        Medicine_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Medicine_InfoMouseMoved

    private void Medicine_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Medicine_InfoMouseClicked
        Medicine_Info.setBackground(new Color(0,0,255).brighter());
        Medicine_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Medicine_InfoMouseClicked

    private void Medicine_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Medicine_InfoMouseEntered
        Medicine_Info.setBackground(new Color(0,153,255).brighter());
        Medicine_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Medicine_InfoMouseEntered

    private void Medicine_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Medicine_InfoMouseExited
        Medicine_Info.setBackground(new Color(232,245,253));
        Medicine_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Medicine_InfoMouseExited

    private void Medicine_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Medicine_InfoMousePressed
        Medicine_Info.setBackground(new Color(0,0,255).brighter());
        Medicine_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Medicine_InfoMousePressed

    private void Medicine_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Medicine_InfoMouseReleased
        Medicine_Info.setBackground(new Color(232,245,253));
        Medicine_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Medicine_InfoMouseReleased

    private void Medicine_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Medicine_InfoActionPerformed
        new Medicine_List().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_Medicine_InfoActionPerformed

    private void Test_ListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseMoved
        Test_List.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Test_ListMouseMoved

    private void Test_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseClicked
        Test_List.setBackground(new Color(0,0,255).brighter());
        Test_List.setForeground(Color.WHITE);
    }//GEN-LAST:event_Test_ListMouseClicked

    private void Test_ListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseEntered
        Test_List.setBackground(new Color(0,153,255).brighter());
        Test_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Test_ListMouseEntered

    private void Test_ListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseExited
        Test_List.setBackground(new Color(232,245,253));
        Test_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Test_ListMouseExited

    private void Test_ListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMousePressed
        Test_List.setBackground(new Color(0,0,255).brighter());
        Test_List.setForeground(Color.WHITE);
    }//GEN-LAST:event_Test_ListMousePressed

    private void Test_ListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseReleased
        Test_List.setBackground(new Color(232,245,253));
        Test_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Test_ListMouseReleased

    private void Test_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test_ListActionPerformed
        new Test_Info().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_Test_ListActionPerformed

    private void BackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseMoved
        Back.setCursor(SignIN.cursor);
    }//GEN-LAST:event_BackMouseMoved

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        Back.setBackground(new Color(0,0,255).brighter());
        Back.setForeground(Color.WHITE);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        Back.setBackground(new Color(0,153,255).brighter());
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back.setBackground(new Color(232,245,253));
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMouseExited

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        Back.setBackground(new Color(0,0,255).brighter());
        Back.setForeground(Color.WHITE);
    }//GEN-LAST:event_BackMousePressed

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
        Back.setBackground(new Color(232,245,253));
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMouseReleased

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Chamber_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chamber_InfoMouseMoved
        Chamber_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Chamber_InfoMouseMoved

    private void Chamber_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chamber_InfoMouseClicked
        Chamber_Info.setBackground(new Color(0,0,255).brighter());
        Chamber_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Chamber_InfoMouseClicked

    private void Chamber_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chamber_InfoMouseEntered
        Chamber_Info.setBackground(new Color(0,153,255).brighter());
        Chamber_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Chamber_InfoMouseEntered

    private void Chamber_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chamber_InfoMouseExited
        Chamber_Info.setBackground(new Color(232,245,253));
        Chamber_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Chamber_InfoMouseExited

    private void Chamber_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chamber_InfoMousePressed
        Chamber_Info.setBackground(new Color(0,0,255).brighter());
        Chamber_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Chamber_InfoMousePressed

    private void Chamber_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chamber_InfoMouseReleased
        Chamber_Info.setBackground(new Color(232,245,253));
        Chamber_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Chamber_InfoMouseReleased

    private void Chamber_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chamber_InfoActionPerformed
        try {
            new Chamber_Info().setVisible(true);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_Chamber_InfoActionPerformed

    private void All_PrescriptionsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_All_PrescriptionsMouseMoved
        All_Prescriptions.setCursor(SignIN.cursor);
    }//GEN-LAST:event_All_PrescriptionsMouseMoved

    private void All_PrescriptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_All_PrescriptionsMouseClicked
        All_Prescriptions.setBackground(new Color(0,0,255).brighter());
        All_Prescriptions.setForeground(Color.WHITE);
    }//GEN-LAST:event_All_PrescriptionsMouseClicked

    private void All_PrescriptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_All_PrescriptionsMouseEntered
        All_Prescriptions.setBackground(new Color(0,153,255).brighter());
        All_Prescriptions.setForeground(Color.BLACK);
    }//GEN-LAST:event_All_PrescriptionsMouseEntered

    private void All_PrescriptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_All_PrescriptionsMouseExited
        All_Prescriptions.setBackground(new Color(232,245,253));
        All_Prescriptions.setForeground(Color.BLACK);
    }//GEN-LAST:event_All_PrescriptionsMouseExited

    private void All_PrescriptionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_All_PrescriptionsMousePressed
        All_Prescriptions.setBackground(new Color(0,0,255).brighter());
        All_Prescriptions.setForeground(Color.WHITE);
    }//GEN-LAST:event_All_PrescriptionsMousePressed

    private void All_PrescriptionsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_All_PrescriptionsMouseReleased
        All_Prescriptions.setBackground(new Color(232,245,253));
        All_Prescriptions.setForeground(Color.BLACK);
    }//GEN-LAST:event_All_PrescriptionsMouseReleased

    private void All_PrescriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_All_PrescriptionsActionPerformed
        new Prescription_List().setVisible(true);
    }//GEN-LAST:event_All_PrescriptionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton All_Prescriptions;
    private javax.swing.JButton Back;
    private javax.swing.JButton Chamber_Info;
    private javax.swing.JButton Medicine_Info;
    private javax.swing.JButton Patient_Info;
    private javax.swing.JButton Test_List;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
