/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyProject;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.text.*;
import java.util.Date;

/**
 *
 * @author Md. Younus Hossain Ahsan
 */

public class Menu extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    
    Timer timer;
    SimpleDateFormat rdf = new SimpleDateFormat("HH");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        
    public Menu() {
        initComponents();
        
        timer = new Timer(1000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                               
                Date CurrentDate = new Date();
                int check = Integer.parseInt(rdf.format(CurrentDate));
                if(check > 11)
                    Date.setText(sdf.format(CurrentDate) + " PM");
                else
                    Date.setText(sdf.format(CurrentDate) + " AM");
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        New_Appointment = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        Test_List = new javax.swing.JButton();
        Appointment_List = new javax.swing.JButton();
        Personal_Info = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Menu_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        New_Appointment.setBackground(new java.awt.Color(232, 245, 253));
        New_Appointment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        New_Appointment.setText("New Appointment");
        New_Appointment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        New_Appointment.setContentAreaFilled(false);
        New_Appointment.setOpaque(true);
        New_Appointment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                New_AppointmentMouseMoved(evt);
            }
        });
        New_Appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_AppointmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                New_AppointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                New_AppointmentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                New_AppointmentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                New_AppointmentMouseReleased(evt);
            }
        });
        New_Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_AppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(New_Appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 200, 45));

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(232, 245, 253));
        Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setBorder(null);
        Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
        });
        Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateMouseClicked(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 200, -1));

        Test_List.setBackground(new java.awt.Color(232, 245, 253));
        Test_List.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Test_List.setText("Information Panel");
        Test_List.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Test_List.setContentAreaFilled(false);
        Test_List.setOpaque(true);
        Test_List.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Test_ListMouseMoved(evt);
            }
        });
        Test_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Test_ListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Test_ListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Test_ListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Test_ListMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Test_ListMouseReleased(evt);
            }
        });
        Test_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test_ListActionPerformed(evt);
            }
        });
        getContentPane().add(Test_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 200, 45));

        Appointment_List.setBackground(new java.awt.Color(232, 245, 253));
        Appointment_List.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Appointment_List.setText("Appointment List");
        Appointment_List.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Appointment_List.setContentAreaFilled(false);
        Appointment_List.setOpaque(true);
        Appointment_List.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Appointment_ListMouseMoved(evt);
            }
        });
        Appointment_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Appointment_ListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Appointment_ListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Appointment_ListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Appointment_ListMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Appointment_ListMouseReleased(evt);
            }
        });
        Appointment_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Appointment_ListActionPerformed(evt);
            }
        });
        getContentPane().add(Appointment_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, 45));

        Personal_Info.setBackground(new java.awt.Color(232, 245, 253));
        Personal_Info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Personal_Info.setText("Personal Info");
        Personal_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Personal_Info.setContentAreaFilled(false);
        Personal_Info.setOpaque(true);
        Personal_Info.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Personal_InfoMouseMoved(evt);
            }
        });
        Personal_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Personal_InfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Personal_InfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Personal_InfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Personal_InfoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Personal_InfoMouseReleased(evt);
            }
        });
        Personal_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personal_InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Personal_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 200, 45));

        Exit.setBackground(new java.awt.Color(232, 245, 253));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Exit.setContentAreaFilled(false);
        Exit.setOpaque(true);
        Exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ExitMouseMoved(evt);
            }
        });
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ExitMouseReleased(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 200, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/icon_2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, 200));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/+.png"))); // NOI18N
        jLabel4.setText(" Medicine Prescribing System ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 110));

        Menu_icon.setBackground(new java.awt.Color(255, 255, 255));
        Menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/bg2.jpg"))); // NOI18N
        getContentPane().add(Menu_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Test_ListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseMoved
        Test_List.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Test_ListMouseMoved

    private void Test_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseClicked
        Test_List.setBackground(new Color(0,0,255).brighter());
        Test_List.setForeground(Color.WHITE);
    }//GEN-LAST:event_Test_ListMouseClicked

    private void Test_ListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseEntered
        Test_List.setBackground(new Color(0,153,255).brighter());
        Test_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Test_ListMouseEntered

    private void Test_ListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseExited
        Test_List.setBackground(new Color(232,245,253));
        Test_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Test_ListMouseExited

    private void Test_ListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMousePressed
        Test_List.setBackground(new Color(0,0,255).brighter());
        Test_List.setForeground(Color.WHITE);
    }//GEN-LAST:event_Test_ListMousePressed

    private void Test_ListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Test_ListMouseReleased
        Test_List.setBackground(new Color(232,245,253));
        Test_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Test_ListMouseReleased

    private void Test_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test_ListActionPerformed
        new Information_Panel().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_Test_ListActionPerformed

    private void Appointment_ListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Appointment_ListMouseMoved
        Appointment_List.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Appointment_ListMouseMoved

    private void Appointment_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Appointment_ListMouseClicked
        Appointment_List.setBackground(new Color(0,0,255).brighter());
        Appointment_List.setForeground(Color.WHITE);
    }//GEN-LAST:event_Appointment_ListMouseClicked

    private void Appointment_ListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Appointment_ListMouseEntered
        Appointment_List.setBackground(new Color(0,153,255).brighter());
        Appointment_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Appointment_ListMouseEntered

    private void Appointment_ListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Appointment_ListMouseExited
        Appointment_List.setBackground(new Color(232,245,253));
        Appointment_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Appointment_ListMouseExited

    private void Appointment_ListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Appointment_ListMousePressed
        Appointment_List.setBackground(new Color(0,0,255).brighter());
        Appointment_List.setForeground(Color.WHITE);
    }//GEN-LAST:event_Appointment_ListMousePressed

    private void Appointment_ListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Appointment_ListMouseReleased
        Appointment_List.setBackground(new Color(232,245,253));
        Appointment_List.setForeground(Color.BLACK);
    }//GEN-LAST:event_Appointment_ListMouseReleased

    private void Appointment_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Appointment_ListActionPerformed
        new Appointment_List().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_Appointment_ListActionPerformed

    private void Personal_InfoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personal_InfoMouseMoved
        Personal_Info.setCursor(SignIN.cursor);
    }//GEN-LAST:event_Personal_InfoMouseMoved

    private void Personal_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personal_InfoMouseClicked
        Personal_Info.setBackground(new Color(0,0,255).brighter());
        Personal_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Personal_InfoMouseClicked

    private void Personal_InfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personal_InfoMouseEntered
        Personal_Info.setBackground(new Color(0,153,255).brighter());
        Personal_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Personal_InfoMouseEntered

    private void Personal_InfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personal_InfoMouseExited
        Personal_Info.setBackground(new Color(232,245,253));
        Personal_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Personal_InfoMouseExited

    private void Personal_InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personal_InfoMousePressed
        Personal_Info.setBackground(new Color(0,0,255).brighter());
        Personal_Info.setForeground(Color.WHITE);
    }//GEN-LAST:event_Personal_InfoMousePressed

    private void Personal_InfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personal_InfoMouseReleased
        Personal_Info.setBackground(new Color(232,245,253));
        Personal_Info.setForeground(Color.BLACK);
    }//GEN-LAST:event_Personal_InfoMouseReleased

    private void Personal_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personal_InfoActionPerformed
        /*
        VericationCodeSend verification = new VericationCodeSend();
        verification.Set();
        verification.Code_Generate();
        verification.Find_Recipient();
        try {
            verification.Code_Send();
            
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Verify("Personal Information").setVisible(true);
        */
        try{
            new Personal_Info().setVisible(true);
        }catch(Exception e){}        
        //dispose();
    }//GEN-LAST:event_Personal_InfoActionPerformed

    private void ExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseMoved
        Exit.setCursor(SignIN.cursor);
    }//GEN-LAST:event_ExitMouseMoved

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        Exit.setBackground(new Color(0,0,255).brighter());
        Exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        Exit.setBackground(new Color(0,153,255).brighter());
        Exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        Exit.setBackground(new Color(232,245,253));
        Exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        Exit.setBackground(new Color(0,0,255).brighter());
        Exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_ExitMousePressed

    private void ExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseReleased
        Exit.setBackground(new Color(232,245,253));
        Exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_ExitMouseReleased

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int result = JOptionPane.showConfirmDialog(this,"Do you want to close ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                
        if(result == JOptionPane.YES_OPTION){
           
              System.exit(0);              
        }   
    }//GEN-LAST:event_ExitActionPerformed

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFocusGained

    private void DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateMouseClicked

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void New_AppointmentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_AppointmentMouseMoved
        New_Appointment.setCursor(SignIN.cursor);
    }//GEN-LAST:event_New_AppointmentMouseMoved

    private void New_AppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_AppointmentMouseClicked
        New_Appointment.setBackground(new Color(0,0,255).brighter());
        New_Appointment.setForeground(Color.WHITE);
    }//GEN-LAST:event_New_AppointmentMouseClicked

    private void New_AppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_AppointmentMouseEntered
        New_Appointment.setBackground(new Color(0,153,255).brighter());
        New_Appointment.setForeground(Color.BLACK);
    }//GEN-LAST:event_New_AppointmentMouseEntered

    private void New_AppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_AppointmentMouseExited
        New_Appointment.setBackground(new Color(232,245,253));
        New_Appointment.setForeground(Color.BLACK);
    }//GEN-LAST:event_New_AppointmentMouseExited

    private void New_AppointmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_AppointmentMousePressed
        New_Appointment.setBackground(new Color(0,0,255).brighter());
        New_Appointment.setForeground(Color.WHITE);
    }//GEN-LAST:event_New_AppointmentMousePressed

    private void New_AppointmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_AppointmentMouseReleased
        New_Appointment.setBackground(new Color(232,245,253));
        New_Appointment.setForeground(Color.BLACK);
    }//GEN-LAST:event_New_AppointmentMouseReleased

    private void New_AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_AppointmentActionPerformed
        try {
            new New_Appointment().setVisible(true);
        } catch (ClassNotFoundException ex) {            
        }
        //dispose();
    }//GEN-LAST:event_New_AppointmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appointment_List;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Menu_icon;
    private javax.swing.JButton New_Appointment;
    private javax.swing.JButton Personal_Info;
    private javax.swing.JButton Test_List;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
