/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyProject;

import JClasses.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.text.*;
import java.util.Date;
import java.util.logging.*;
import javax.swing.Timer;

/**
 *
 * @author Md. Younus Hossain Ahsan
 */

public class SignIN extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
        
    Timer timer;
    SimpleDateFormat rdf = new SimpleDateFormat("HH");    
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
    SimpleDateFormat tdf = new SimpleDateFormat("yy/MM/dd");
    public static String EmailID = "";
    public static String EmailPassword = "";
    public static Cursor cursor = new Cursor(Cursor.HAND_CURSOR);
        
    
       
    public SignIN() throws ClassNotFoundException {
        
        initComponents();
                
        EmailID = SE.getText();
        EmailPassword = SEP.getText();
        
        Date CurrentDate = new Date();                
        Appointment appointment = new Appointment();
        
        
        
        appointment.Delete_All_the_Previous_Appointments(tdf.format(CurrentDate));
        
        timer = new Timer(1000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                Date CurrentDate = new Date(); 
                
                int check = Integer.parseInt(rdf.format(CurrentDate));
                if(check > 11)
                    Date.setText(sdf.format(CurrentDate) + " PM");
                else
                    Date.setText(sdf.format(CurrentDate) + " AM");
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        timer.start();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SE = new javax.swing.JLabel();
        SEP = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        User_Name = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        ShowPassword = new javax.swing.JCheckBox();
        Sign_IN = new javax.swing.JButton();
        Forgot = new javax.swing.JLabel();
        background_icon = new javax.swing.JLabel();

        SE.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        SE.setForeground(new java.awt.Color(255, 255, 255));
        SE.setText("email ID");
        SE.setToolTipText("");

        SEP.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        SEP.setForeground(new java.awt.Color(255, 255, 255));
        SEP.setText("p@ssword");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(232, 245, 253));
        Date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date.setBorder(null);
        Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DateFocusGained(evt);
            }
        });
        Date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateMouseClicked(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 232, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/+.png"))); // NOI18N
        jLabel2.setText(" Welcome to the Medicine Prescribing System ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 900, 56));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/icon_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 190));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/user.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 40));

        User_Name.setBackground(new java.awt.Color(232, 245, 253));
        User_Name.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        User_Name.setText("User Name");
        User_Name.setBorder(null);
        User_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                User_NameFocusGained(evt);
            }
        });
        User_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User_NameMouseClicked(evt);
            }
        });
        User_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_NameActionPerformed(evt);
            }
        });
        getContentPane().add(User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 220, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 153, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setFocusable(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 220, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/password.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, 35));

        Password.setBackground(new java.awt.Color(232, 245, 253));
        Password.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        Password.setText("Password");
        Password.setBorder(null);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
        });
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 220, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 220, 10));

        ShowPassword.setBackground(new java.awt.Color(232, 245, 253));
        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 290, 141, -1));

        Sign_IN.setBackground(new java.awt.Color(232, 245, 253));
        Sign_IN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sign_IN.setText("Sign IN");
        Sign_IN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        Sign_IN.setContentAreaFilled(false);
        Sign_IN.setOpaque(true);
        Sign_IN.setVerifyInputWhenFocusTarget(false);
        Sign_IN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Sign_INMouseMoved(evt);
            }
        });
        Sign_IN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_INMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Sign_INMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Sign_INMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Sign_INMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Sign_INMouseReleased(evt);
            }
        });
        Sign_IN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_INActionPerformed(evt);
            }
        });
        getContentPane().add(Sign_IN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 90, 40));

        Forgot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Forgot.setForeground(new java.awt.Color(204, 0, 0));
        Forgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Forgot.setText("Do you forget your password ?");
        Forgot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ForgotMouseMoved(evt);
            }
        });
        Forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForgotMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ForgotMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ForgotMouseReleased(evt);
            }
        });
        getContentPane().add(Forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 390, 260, -1));

        background_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_images/bg1.jpg"))); // NOI18N
        getContentPane().add(background_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_User_NameFocusGained

    }//GEN-LAST:event_User_NameFocusGained

    private void User_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_NameMouseClicked
        // TODO add your handling code here:
        User_Name.setText("");
    }//GEN-LAST:event_User_NameMouseClicked

    private void User_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_NameActionPerformed

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained

    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        // TODO add your handling code here:
        Password.setText("");
    }//GEN-LAST:event_PasswordMouseClicked

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        if(ShowPassword.isSelected())
        {
            Password.setEchoChar((char) 0);
        }else{
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void Sign_INActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_INActionPerformed
        
//        DoctorInfo doctor_Profile = new DoctorInfo();
//        
//        try {
//            doctor_Profile.search();
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(SignIN.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        
//        if(User_Name.getText().equals("User Name") && Password.getText().equals("Password"))
//        {
//            JOptionPane.showMessageDialog(null, "Enter the username and password !!!");
//        }
//        else if(User_Name.getText().trim().equals("") && Password.getText().trim().equals(""))
//        {
//            JOptionPane.showMessageDialog(null, "Enter the username and password !!!");
//        }        
//        else if(User_Name.getText().trim().equals(""))
//        {
//            JOptionPane.showMessageDialog(null, "Enter the username !!!");
//        }
//        else if(Password.getText().trim().equals(""))
//        {
//            Sign_IN.setEnabled(true);
//            JOptionPane.showMessageDialog(null, "Enter the password !!!");
//        }
//        else if(User_Name.getText().equals(doctor_Profile.getUsername()) && Password.getText().equals(doctor_Profile.getPassword()))
//        {
//            JOptionPane.showMessageDialog(null, "Successfully done !!!");
//            new Menu().setVisible(true);
//            this.setVisible(false);
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "Not matched !!!");        
//        }        
        
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Sign_INActionPerformed

    private void ForgotMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseMoved
        Forgot.setCursor(cursor);
    }//GEN-LAST:event_ForgotMouseMoved

    private void ForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseClicked
        
        Forgot.setForeground(new Color(179, 45, 45));
        VericationCodeSend verification = new VericationCodeSend();
        verification.Set();
        verification.Code_Generate();
        verification.Find_Recipient();
        
        try {
            verification.Code_Send();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(SignIN.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Verify("Sign IN").setVisible(true);
        dispose();
    }//GEN-LAST:event_ForgotMouseClicked

    private void DateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFocusGained

    private void DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateMouseClicked

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void Sign_INMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_INMouseMoved
        Sign_IN.setCursor(cursor);
    }//GEN-LAST:event_Sign_INMouseMoved

    private void Sign_INMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_INMouseClicked
        Sign_IN.setBackground(new Color(0,0,255).brighter());
        Sign_IN.setForeground(Color.WHITE);
    }//GEN-LAST:event_Sign_INMouseClicked

    private void Sign_INMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_INMouseEntered
        Sign_IN.setBackground(new Color(0,153,255).brighter());
        Sign_IN.setForeground(Color.BLACK);
    }//GEN-LAST:event_Sign_INMouseEntered

    private void Sign_INMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_INMouseExited
        Sign_IN.setBackground(new Color(232,245,253));
        Sign_IN.setForeground(Color.BLACK);
    }//GEN-LAST:event_Sign_INMouseExited

    private void Sign_INMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_INMousePressed
        Sign_IN.setBackground(new Color(0,0,255).brighter());
        Sign_IN.setForeground(Color.WHITE);
    }//GEN-LAST:event_Sign_INMousePressed

    private void Sign_INMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_INMouseReleased
        Sign_IN.setBackground(new Color(232,245,253));
        Sign_IN.setForeground(Color.BLACK);
    }//GEN-LAST:event_Sign_INMouseReleased

    private void ForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseEntered
        Forgot.setForeground(new Color(179, 45, 45).brighter());
    }//GEN-LAST:event_ForgotMouseEntered

    private void ForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseExited
        Forgot.setForeground(new Color(255, 0, 0));
    }//GEN-LAST:event_ForgotMouseExited

    private void ForgotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMousePressed
        Forgot.setForeground(new Color(232,245,253));
    }//GEN-LAST:event_ForgotMousePressed

    private void ForgotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotMouseReleased
        Forgot.setForeground(new Color(255, 0, 0));
    }//GEN-LAST:event_ForgotMouseReleased

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SignIN().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SignIN.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JLabel Forgot;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SE;
    private javax.swing.JLabel SEP;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JButton Sign_IN;
    private javax.swing.JTextField User_Name;
    private javax.swing.JLabel background_icon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
